### ISSUE TITLE
大兄弟，我按你的方案1.5成功了，但是同样的步骤编译1.6就不行了。你有没有试过呢？

### ISSUE THREAD

**Issue by shifeng1993** [geekcui/tensorflow-macos-egpu#1]

**Comment by geekcui** [comment]
@shifeng1993 
抱歉，回复晚了。
能否提供下错误信息？
我今天晚上尝试编译下。

**Comment by geekcui** [comment]
参考一下这个链接的内容：https://github.com/tensorflow/tensorflow/issues/17067
